server:
  port: 8081
spring:
  application:
    name: stock-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stock_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
      config:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
  config:
    import: optional:nacos:common
# Dubbo配置
dubbo:
  application:
    name: stock-server-rpc
    parameters:
      services-type: dubbo-rpc
  registry:
    address: nacos://127.0.0.1:8848
    username: nacos
    password: nacos
    parameters:
      services-type: dubbo-rpc
  protocol:
    name: tri
    port: 50051
  scan:
    base-packages: com.cloud.stock.service.impl

# MyBatis-Plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com.cloud.stock: debug
