spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # 使用OAuth2提供的JWK端点进行JWT验证
          jwk-set-uri: http://localhost:8082/oauth2/jwks

# JWT密钥配置（用于向后兼容）
jwt:
  secret: mySecretKey1234567890123456 # 至少32位的密钥