spring:
  cloud:
    stream:
      rocketmq:
        bindings:
          stockReserveRequestConsumer-in-0:
            consumer:
              group: stock-reserve-request-consumer-group
          stockReleaseRequestConsumer-in-0:
            consumer:
              group: stock-release-request-consumer-group
          stockConfirmRequestConsumer-in-0:
            consumer:
              group: stock-confirm-request-consumer-group
      bindings:
        stockReserveRequestConsumer-in-0:
          destination: stock-reserve-request
          content-type: application/json
          group: stock-reserve-request-consumer-group
        stockReleaseRequestConsumer-in-0:
          destination: stock-release-request
          content-type: application/json
          group: stock-release-request-consumer-group
        stockConfirmRequestConsumer-in-0:
          destination: stock-confirm-request
          content-type: application/json
          group: stock-confirm-request-consumer-group
        stockFreezeFailedProducer-out-0:
          destination: stock-freeze-failed
          content-type: application/json
        stockAlertProducer-out-0:
          destination: stock-alert
          content-type: application/json
        productSyncProducer-out-0:
          destination: product-sync
          content-type: application/json
