spring:
  cloud:
    stream:
      bindings:
        userProfileSyncProducer-out-0:
          destination: user-profile-sync
          content-type: application/json
          group: auth-user-profile-sync-producer
