spring:
  profiles:
    include: auth
  application:
    name: auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
      config:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
  config:
    import: optional:nacos:common
  data:
    redis:
      host: localhost
      port: 6379
      password: root # 若无需密码则删除此行
      database: 0 # 默认 DB
      jedis:
        pool:
          max-active: 20   # 最大连接数
          max-wait: 2000ms # 最大等待时间
      username: root



server:
  port: 8082

dubbo:
  application:
    name: auth-server
    qos-enable: false
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    port: 20881
  consumer:
    timeout: 5000

logging:
  file:
    path: D:/logs/${spring.application.name}
    name: ${logging.file.path}/${spring.application.name}.log
