server:
  port: 8082
spring:
  application:
    name: auth-service
  profiles:
    include: auth
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: dev
        group: DEFAULT_GROUP
      config:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: dev
        file-extension: yaml
        group: DEFAULT_GROUP
  config:
    import: optional:nacos:common
  data:
    redis:
      host: localhost
      port: 6379
      password: root # 若无需密码则删除此行
      database: 0 # 默认 DB
      jedis:
        pool:
          max-active: 20   # 最大连接数
          max-wait: 2000ms # 最大等待时间
      username: root


dubbo:
  registry:
    address: nacos://${spring.cloud.nacos.discovery.server-addr}?namespace=${spring.cloud.nacos.discovery.namespace}
    username: nacos
    password: nacos
    parameters:
      services-type: dubbo-rpc
  consumer:
    check: false

logging:
  file:
    path: D:/logs/${spring.application.name}
    name: ${logging.file.path}/${spring.application.name}.log

# Knife4j配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: auth
      paths-to-match: /**
      packages-to-scan: com.cloud.auth.controller

knife4j:
  enable: true
  production: false
  basic:
    enable: true
    username: admin
    password: admin123