spring:
  cloud:
    stream:
      bindings:
        refundCompletedProducer-out-0:
          destination: refund-completed
          content-type: application/json

rocketmq:
  producer:
    group: ${ROCKETMQ_PRODUCER_GROUP:payment-success-tx-group}
