spring:
  application:
    name: auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
      config:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
  config:
    import: optional:nacos:common


server:
  port: 8082
logging:
  file:
    path: D:/logs/${spring.application.name}
    name: ${logging.file.path}/stock.log
