# RocketMQ配置文件 - 用户服务
spring:
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: ${ROCKETMQ_NAME_SERVER:127.0.0.1:39876}
          group: user-service-group
        bindings:
          # 日志收集生产者
          logProducer-out-0:
            producer:
              group: user-log-producer-group
              send-message-timeout: 3000
              compress-message-body-threshold: 4096
              max-message-size: 4194304
              retry-times-when-send-failed: 2
              retry-times-when-send-async-failed: 2
      bindings:
        # 日志收集生产者绑定
        logProducer-out-0:
          destination: log-collection-topic
          content-type: application/json
          producer:
            partition-count: 4
            use-native-encoding: true
      function:
        definition: ""

# 日志配置
logging:
  level:
    com.cloud.user.messaging: DEBUG
    org.springframework.cloud.stream: DEBUG
    org.apache.rocketmq: INFO
