modules:
  http_2xx:
    prober: http
    timeout: 8s
    http:
      preferred_ip_protocol: ip4
      method: GET
      valid_http_versions:
        - "HTTP/1.1"
        - "HTTP/2"
      no_follow_redirects: false
  tcp_connect:
    prober: tcp
    timeout: 8s
    tcp:
      preferred_ip_protocol: ip4
