spring:
  cloud:
    stream:
      bindings:
        orderLog-out-0:
          destination: LOG_ORDER_TOPIC
          content-type: application/json
          producer:
            partition-count: 4
        orderToPayment-out-0:
          destination: ORDER_TO_PAYMENT_TOPIC
          content-type: application/json
        orderToStock-out-0:
          destination: ORDER_TO_STOCK_TOPIC
          content-type: application/json
        order-producer-out-0:
          destination: order-events
          content-type: application/json
          group: order-producer-group
          producer:
            maxRequestSize: 4194304
            sync: true
        orderShippedConsumer-in-0:
          destination: order-shipped
          content-type: application/json
          group: order-shipped-consumer-group
        orderAutoReceiveProducer-out-0:
          destination: order-auto-receive
          content-type: application/json
        orderAutoReceiveConsumer-in-0:
          destination: order-auto-receive
          content-type: application/json
          group: order-auto-receive-consumer-group
