spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:prod-mysql}:${DB_PORT:3306}/order_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    druid:
      initial-size: 12
      min-idle: 12
      max-active: 40
      max-wait: 30000
      keep-alive: true
      async-init: true
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validation-query: SELECT 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
  data:
    redis:
      host: ${REDIS_HOST:prod-redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      database: 3
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 32
          max-wait: -1ms
          max-idle: 16
          min-idle: 4
logging:
  level:
    com.cloud.order: info
    org.springframework.security: warn
    org.springframework.web: warn
    com.alibaba.nacos: warn
    root: warn
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
knife4j:
  enable: false
  production: true
  basic:
    enable: true
    username: ${API_DOC_USERNAME}
    password: ${API_DOC_PASSWORD}



