# RocketMQ配置文件 - 商品服务
spring:
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: ${ROCKETMQ_NAME_SERVER:127.0.0.1:39876}
          group: product-service-group
        bindings:
          # 日志收集生产者
          logProducer-out-0:
            producer:
              group: product-log-producer-group
              send-message-timeout: 3000
              compress-message-body-threshold: 4096
              max-message-size: 4194304
              retry-times-when-send-failed: 2
          # 商品搜索事件生产者
          productSearchProducer-out-0:
            producer:
              group: product-search-producer-group
              send-message-timeout: 3000
              compress-message-body-threshold: 4096
              max-message-size: 4194304
              retry-times-when-send-failed: 2
          # 统一业务日志生产者
          businessLog-out-0:
            producer:
              group: product-business-log-producer-group
              send-message-timeout: 3000
              compress-message-body-threshold: 4096
              max-message-size: 4194304
              retry-times-when-send-failed: 2
      bindings:
        # 日志收集生产者绑定
        logProducer-out-0:
          destination: log-collection-topic
          content-type: application/json
          producer:
            partition-count: 4
            use-native-encoding: true
        # 商品搜索事件生产者绑定
        productSearchProducer-out-0:
          destination: product-search-topic
          content-type: application/json
          producer:
            partition-count: 4
            use-native-encoding: true
        # 统一业务日志生产者绑定
        businessLog-out-0:
          destination: business-log-topic
          content-type: application/json
          producer:
            partition-count: 4
            use-native-encoding: true
      function:
        definition: ""

# 日志配置
logging:
  level:
    com.cloud.product.messaging: DEBUG
    org.springframework.cloud.stream: DEBUG
    org.apache.rocketmq: INFO
