server:
  port: 8090
spring:
  application:
    name: log-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8082/oauth2/jwks
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: public
        group: DEFAULT_GROUP
      config:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: public
        file-extension: yaml
        group: DEFAULT_GROUP
    stream:
      bindings:
        userLog-in-0:
          destination: LOG_USER_TOPIC
          content-type: application/json
          group: log-group
        merchantLog-in-0:
          destination: LOG_MERCHANT_TOPIC
          content-type: application/json
          group: log-group
        adminLog-in-0:
          destination: LOG_ADMIN_TOPIC
          content-type: application/json
          group: log-group
        productLog-in-0:
          destination: LOG_PRODUCT_TOPIC
          content-type: application/json
          group: log-group
        orderLog-in-0:
          destination: LOG_ORDER_TOPIC
          content-type: application/json
          group: log-group
        paymentLog-in-0:
          destination: LOG_PAYMENT_TOPIC
          content-type: application/json
          group: log-group
        stockLog-in-0:
          destination: LOG_STOCK_TOPIC
          content-type: application/json
          group: log-group
  config:
    import: optional:nacos:common
  data:
    redis:
      host: localhost
      port: 6379
      password: root
      database: 0
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
    elasticsearch:
      repositories:
        enabled: true
elasticsearch:
  url: http://localhost:9201
logging:
  file:
    path: D:/logs/${spring.application.name}
    name: ${logging.file.path}/${spring.application.name}.log