server:
  port: 8087
spring:
  application:
    name: log-service
  security:
    oauth2:
      resourceserver:
        jwt:
          # 通过网关访问 OAuth2.1 授权服务器的 JWK 端点
          jwk-set-uri: http://127.0.0.1:80/.well-known/jwks.json
          cache-duration: PT30M
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: public
        group: DEFAULT_GROUP
      config:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: public
        file-extension: yaml
        group: DEFAULT_GROUP
    stream:
      function:
        definition: userEventConsumer
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
        bindings:
          userEventConsumer-in-0:
            consumer:
              # 指定订阅的Tag，多个Tag用||分隔
              subscription: 'user-created||user-updated||user-deleted||user-status-changed'
              push:
                orderly: false
      bindings:
        userEventConsumer-in-0:
          destination: user-events
          content-type: application/json
          group: log-service-group
        userLog-in-0:
          destination: LOG_USER_TOPIC
          content-type: application/json
          group: log-group
        merchantLog-in-0:
          destination: LOG_MERCHANT_TOPIC
          content-type: application/json
          group: log-group
        adminLog-in-0:
          destination: LOG_ADMIN_TOPIC
          content-type: application/json
          group: log-group
        productLog-in-0:
          destination: LOG_PRODUCT_TOPIC
          content-type: application/json
          group: log-group
        orderLog-in-0:
          destination: LOG_ORDER_TOPIC
          content-type: application/json
          group: log-group
        paymentLog-in-0:
          destination: LOG_PAYMENT_TOPIC
          content-type: application/json
          group: log-group
        stockLog-in-0:
          destination: LOG_STOCK_TOPIC
          content-type: application/json
          group: log-group
        // 添加其他服务日志topic
        authLog-in-0:
          destination: LOG_AUTH_TOPIC
          content-type: application/json
          group: log-group
        gatewayLog-in-0:
          destination: LOG_GATEWAY_TOPIC
          content-type: application/json
          group: log-group
  config:
    import: optional:nacos:common
  data:
    redis:
      host: localhost
      port: 6379
      password: root
      database: 0
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
    elasticsearch:
      repositories:
        enabled: true
elasticsearch:
  url: http://localhost:9201
logging:
  file:
    path: D:/logs/${spring.application.name}
    name: ${logging.file.path}/${spring.application.name}.log