# 订单事件消费配置
spring:
  cloud:
    stream:
      # 函数定义
      function:
        definition: orderConsumer

      # RocketMQ绑定配置
      bindings:
        # 订单事件消费者绑定
        orderConsumer-in-0:
          destination: order-events
          content-type: application/json
          group: log-service-order-group
          consumer:
            maxAttempts: 3
            backOffInitialInterval: 1000
            backOffMaxInterval: 10000
            backOffMultiplier: 2.0

      # RocketMQ消费者配置
      rocketmq:
        bindings:
          orderConsumer-in-0:
            consumer:
              # 订阅所有订单事件标签
              subscription: 'order-created||order-paid||order-shipped||order-completed||order-cancelled||order-refunded||order-status-changed||order-timeout'
              # 消息消费模式：集群消费
              messageModel: CLUSTERING
              # 消费者线程数
              consumeThreadMin: 5
              consumeThreadMax: 20
              # 消息拉取数量
              pullBatchSize: 16
              # 消费超时时间
              consumeTimeout: 10000

# 日志配置
logging:
  level:
    com.cloud.log.messaging: DEBUG
    org.springframework.cloud.stream: DEBUG
    com.alibaba.cloud.stream.binder.rocketmq: DEBUG
