server:
  port: ${server.port}
spring:
  profiles:
    active: dev
  application:
    name: ${spring.application.name}
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.discovery.server-addr}
        username: ${nacos.discovery.username}
        password: ${nacos.discovery.password}
        namespace: ${nacos.discovery.namespace}
        group: ${nacos.discovery.group}
      config:
        server-addr: ${nacos.config.server-addr}
        username: ${nacos.config.username}
        password: ${nacos.config.password}
        namespace: ${nacos.config.namespace}
        file-extension: ${nacos.config.file-extension}
        group: ${nacos.config.group}
    stream:
      function:
        definition: genericLogConsumer
      bindings:
        genericLogConsumer-in-0:
          destination: LOG_ADMIN_TOPIC,LOG_MERCHANT_TOPIC,LOG_USER_TOPIC,LOG_PRODUCT_TOPIC,LOG_PAYMENT_TOPIC,LOG_STOCK_TOPIC,LOG_ORDER_TOPIC,PAYMENT_CREATE_TOPIC,STOCK_FREEZE_TOPIC
          group: log-consumer-group
          content-type: application/json
          consumer:
            max-attempts: 3
            back-off-initial-interval: 1000
            back-off-multiplier: 2.0
            back-off-max-interval: 10000
      rocketmq:
        binder:
          name-server: ${rocketmq.name-server}
        bindings:
          genericLogConsumer-in-0:
            consumer:
              push:
                orderly: false

  config:
    import: optional:nacos:common
  datasource:
    driver-class-name: ${spring.datasource.driver-class-name}
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  data:
    redis:
      host: ${spring.redis.host}
      port: ${spring.redis.port}
      password: ${spring.redis.password}
      database: ${spring.redis.database}
      timeout: ${spring.redis.timeout}
      lettuce:
        pool:
          max-active: ${spring.redis.lettuce.pool.max-active}
          max-wait: ${spring.redis.lettuce.pool.max-wait}
          max-idle: ${spring.redis.lettuce.pool.max-idle}
          min-idle: ${spring.redis.lettuce.pool.min-idle}
    elasticsearch:
      repositories:
        enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.jwk-set-uri}
logging:
  file:
    path: D:/logs/${spring.application.name}
    name: ${logging.file.path}/${spring.application.name}.log
  level:
    com.cloud.user.mapper: TRACE
knife4j:
  enable: true
  production: false
  basic:
    enable: false
  setting:
    language: ZH_CN
  insight:
    service-name: ${spring.application.name}

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  default-flat-param-object: true

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml