# 日志服务 - 开发环境配置

spring:
  # Elasticsearch 配置
  data:
    elasticsearch:
      repositories:
        enabled: true

# Elasticsearch 配置
elasticsearch:
  url: http://localhost:9200

# 日志级别配置
logging:
  level:
    com.cloud.log: debug
    org.springframework.security: debug
    org.springframework.web: debug
    org.springframework.cloud.stream: debug
    org.elasticsearch: debug
    com.alibaba.nacos: warn

# Knife4j 开发配置
knife4j:
  enable: true
  production: false
  basic:
    enable: false
