# 开发环境配置文件
server:
  port: 8090
# Nacos配置
nacos:
  discovery:
    server-addr: localhost:8848
    username: nacos
    password: nacos
    namespace: public
    group: DEFAULT_GROUP
  config:
    server-addr: localhost:8848
    username: nacos
    password: nacos
    namespace: public
    file-extension: yaml
    group: DEFAULT_GROUP

# 数据源配置
spring:
  application:
    name: log-service
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/log_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
  data:
    redis:
      host: localhost
      port: 6379
      password: root
      database: 0
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 100      # 高并发场景建议100-200
          max-idle: 50
          min-idle: 20
          max-wait: 2000ms
      connect-timeout: 1000ms
    elasticsearch:
      repositories:
        enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8082/oauth2/jwks
elasticsearch:
  url: http://localhost:9200