# 全局配置
global:
  scrape_interval:     15s # 默认抓取间隔
  evaluation_interval: 15s # 规则评估间隔

# Alertmanager配置
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# 规则文件
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# 抓取配置
scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  # Spring Boot Actuator监控
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: 
      - 'host.docker.internal:8080' # 用户服务
      - 'host.docker.internal:8081' # 库存服务
      - 'host.docker.internal:8082' # 订单服务
      - 'host.docker.internal:8083' # 支付服务
      - 'host.docker.internal:8084' # 商品服务
      - 'host.docker.internal:8085' # 商家服务
      - 'host.docker.internal:8086' # 管理员服务
      - 'host.docker.internal:8087' # 搜索服务
      - 'host.docker.internal:8088' # 认证服务
      - 'host.docker.internal:8089' # 网关服务
    scrape_interval: 10s