spring:
  application:
    name: user-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
      config:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
  config:
    import: optional:nacos:common
  datasource:
    url: jdbc:mysql://localhost:3306/user_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

# JWT密钥配置
jwt:
  secret: mySecretKey1234567890123456 # 至少32位的密钥

server:
  port: 8083

dubbo:
  application:
    name: user-server-rpc
    qos-enable: false
    parameters:
      services-type: dubbo-rpc
  registry:
    address: nacos://127.0.0.1:8848
    username: nacos
    password: nacos
    parameters:
      services-type: dubbo-rpc
  protocol:
    name: dubbo
    port: 20880
  consumer:
    timeout: 5000
logging:
  level:
    com.cloud.user.mapper: TRACE
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml  # XML 扫描路径
  type-aliases-package: com.example.module.entity       # 实体类包别名
  configuration:
    map-underscore-to-camel-case: true           # 驼峰转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # SQL 日志输出
  global-config:
    db-config:
      id-type: assign_id                         # 雪花算法主键
      logic-delete-field: deleted                # 逻辑删除字段
      logic-delete-value: 1                      # 删除标记值
      logic-not-delete-value: 0                  # 未删除标记值

minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: user-avatars
  # 外网访问地址，用于生成可访问的URL
  public-endpoint: http://localhost:9000
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: user
      paths-to-match: /**
      packages-to-scan: com.cloud.user.controller

knife4j:
  enable: true
  production: false
  basic:
    enable: true
    username: admin
    password: admin123